"""Keyword taxonomy definitions for discovery and demographic matching."""

KEYWORD_TAXONOMY: dict[str, list[str]] = {
    "gold_investment": [
        "physical gold", "gold ira", "precious metals", "bullion",
        "silver coins", "gold coins", "gold protects", "gold investment",
    ],
    "retirement": [
        "retirement planning", "social security", "fixed income",
        "401k", "ira rollover", "retirement savings", "pension",
    ],
    "alternative_media_politics": [
        "independent journalism", "free speech", "censorship",
        "constitutional rights", "alternative media",
    ],
    "preparedness_self_reliance": [
        "emergency preparedness", "food storage", "self reliance",
        "survival", "prepper", "water storage",
    ],
    "conservative_politics_commentary": [
        "america first", "small government", "limited government",
        "constitutional republic", "states rights", "election integrity",
        "voter fraud", "ballot harvesting", "border crisis",
        "illegal immigration", "mainstream media bias", "free speech absolutist",
        "woke agenda", "parental rights", "fiscal conservatism",
        "judicial activism",
    ],
    "anti_establishment_independent_news": [
        "independent journalism", "citizen journalism", "watchdog reporting",
        "accountability reporting", "media blackout", "narrative control",
        "corporate media", "legacy media", "censorship", "deplatforming",
        "whistleblower", "foia request", "follow the money",
        "manufactured consent", "regulatory capture",
    ],
    "investigative_journalism": [
        "investigative report", "document leak", "public records",
        "foia documents", "source verification", "offshore accounts",
        "shell companies", "conflict of interest", "procurement fraud",
        "bid rigging", "kickback scheme", "audit trail",
        "ethics violation", "watchdog investigation",
        "accountability journalism",
    ],
    "conspiracy_deep_state_truth_seeker": [
        "deep state", "false flag", "new world order",
        "globalist agenda", "shadow government", "cover up",
        "intel operation", "black budget", "psyop",
        "mass surveillance state", "elite cabal", "manufactured crisis",
        "controlled opposition", "red pill", "truth seeker",
    ],
    "faith_based_biblical_prophecy": [
        "bible prophecy", "end times", "second coming",
        "tribulation", "great tribulation", "rapture",
        "antichrist", "mark of the beast", "book of revelation",
        "millennial kingdom", "spiritual warfare", "gospel truth",
        "biblical worldview", "signs of the times", "kingdom of god",
    ],
    "prepper_survival_homesteading": [
        "emergency preparedness", "disaster supplies kit", "go bag",
        "72 hour kit", "shelter in place", "off grid",
        "grid down", "water filtration", "water storage",
        "long shelf life food", "backup power", "portable generator",
        "first aid kit", "homesteading", "self reliance",
    ],
    "finance_economics_crypto": [
        "sound money", "fiat currency", "currency debasement",
        "inflation hedge", "federal funds rate", "monetary policy",
        "money supply", "de-dollarization", "national debt",
        "banking crisis", "market crash", "bitcoin",
        "self custody", "cold wallet", "stablecoin", "on chain",
    ],
    "health_freedom_alternative_medicine": [
        "medical freedom", "informed consent", "natural health",
        "holistic health", "functional medicine", "integrative medicine",
        "detox protocol", "immune support", "metabolic health",
        "gut health", "hormone balance", "non toxic living",
        "vaccine injury", "health sovereignty", "root cause medicine",
    ],
    "ufos_aliens_exopolitics": [
        "uap", "unidentified anomalous phenomena",
        "unidentified aerial phenomena", "aaro", "ufo disclosure",
        "non human intelligence", "crash retrieval", "reverse engineering",
        "whistleblower testimony", "tic tac uap", "navy encounters",
        "abduction", "contactee", "exopolitics", "alien technology",
    ],
    "military_veteran_national_security": [
        "national security", "threat assessment", "critical infrastructure",
        "service connected disability", "va disability claim",
        "ptsd claim", "va compensation", "veteran benefits",
        "special operations", "rules of engagement", "force readiness",
        "intelligence assessment", "border security", "counterterrorism",
        "transnational threat",
    ],
    "culture_war_social_commentary": [
        "culture war", "cancel culture", "critical race theory",
        "gender ideology", "identity politics", "woke",
        "anti woke", "parental rights", "free speech on campus",
        "dei", "intersectionality", "social engineering",
        "traditional values", "family values", "moral decline",
    ],
    "second_amendment_gun_rights": [
        "second amendment", "gun rights", "right to bear arms",
        "constitutional carry", "shall issue", "open carry",
        "concealed carry", "magazine ban", "assault weapons ban",
        "red flag laws", "self defense", "stand your ground",
        "firearms training", "home defense", "gun control",
    ],
    "tech_privacy_anti_surveillance": [
        "digital privacy", "government surveillance", "mass surveillance",
        "end to end encryption", "metadata", "zero trust",
        "multi factor authentication", "phishing resistant mfa",
        "ransomware", "phishing", "zero day", "vpn",
        "secure messaging", "data broker", "facial recognition",
    ],
    "legal_constitutional_rights": [
        "first amendment", "fourth amendment", "due process",
        "equal protection", "unreasonable search and seizure",
        "search warrant", "probable cause", "exclusionary rule",
        "civil liberties", "constitutional rights", "judicial review",
        "administrative overreach", "qualified immunity",
        "habeas corpus", "bill of rights",
    ],
    "satire_comedy": [
        "political satire", "parody", "spoof",
        "sarcasm", "irony", "comedy sketch",
        "stand up comedy", "satirical monologue", "roast",
        "deadpan", "dark humor", "punchline",
        "clown world", "meme humor", "comedic commentary",
    ],
    "law_enforcement_crime": [
        "organized crime", "human trafficking", "drug trafficking",
        "money laundering", "identity theft", "wire fraud",
        "real estate fraud", "asset forfeiture", "gang violence",
        "cartel activity", "violent crime", "public safety",
        "cold case", "sex trafficking", "financial crimes",
    ],
    "alternative_history_archaeology": [
        "ancient civilizations", "lost civilization", "forbidden archaeology",
        "megalithic structures", "ancient cataclysm", "younger dryas",
        "atlantis theory", "gobekli tepe", "pyramid alignment",
        "ancient artifacts", "suppressed history", "out of place artifact",
        "prehistoric advanced culture", "biblical archaeology",
        "historical revisionism",
    ],
    "spirituality_metaphysical": [
        "higher consciousness", "spiritual awakening", "chakra",
        "energy healing", "aura", "manifestation",
        "law of attraction", "astrology", "numerology",
        "tarot", "divination", "synchronicity",
        "ascension", "shadow work", "third eye",
    ],
    "lds_mormon_community": [
        "book of mormon", "doctrine and covenants", "pearl of great price",
        "ward", "stake", "relief society",
        "elders quorum", "bishop", "temple recommend",
        "patriarchal blessing", "familysearch", "temple ordinances",
        "genealogy work", "general conference", "restoration",
    ],
    "lifestyle_family_travel": [
        "family life", "homeschool family", "parenting tips",
        "marriage advice", "faith and family", "road trip",
        "rv living", "travel vlog", "expat life",
        "budget travel", "family preparedness", "remote lifestyle",
        "digital nomad", "simple living", "work life balance",
    ],
    "other_unclassified": [
        "uncategorized", "misc commentary", "variety channel",
        "general discussion", "open topic", "mixed content",
    ],
}
